server.port=8080

server.connection-timeout=3000
server.tomcat.keep-alive-timeout=3000
spring.mvc.async.request-timeout=3000

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.session.jdbc=DEBUG
logging.level.org.apache.tomcat=DEBUG
#logging.level.org.springframework.security=DEBUG

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.session.jdbc.platform=postgresql
server.servlet.session.timeout=PT2H

spring.sql.init.mode=always

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.schemas=public
spring.datasource.username=postgres
spring.datasource.password=1

logging.level.org.hibernate.SQL=DEBUG
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html